[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"

[[redirects]]
  from = "/api/prints"
  to = "/.netlify/functions/prints"
  status = 200
  force = true